language: shell

os:
  - linux 

arch:
  - amd64
  - arm64

#services:
# - docker
#
#script:
#  - docker build --build-arg "IMG=debian:unstable" "."

addons:
  apt:
    packages:
      - bsd-mailx make vim sharutils

